// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqEbTF0virVzwNDoKv0YsY9OAEnK0LDIw',
    appId: '1:707418014205:web:1b74bbe2fdd997be645994',
    messagingSenderId: '707418014205',
    projectId: 'isometric-playground-321',
    authDomain: 'isometric-playground-321.firebaseapp.com',
    storageBucket: 'isometric-playground-321.firebasestorage.app',
    measurementId: 'G-D2DQHC4BFX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHJRBD7x-6eMDO_S7Fd0cXC02FDYCSeaw',
    appId: '1:707418014205:android:a9c51045cdebe552645994',
    messagingSenderId: '707418014205',
    projectId: 'isometric-playground-321',
    storageBucket: 'isometric-playground-321.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGy3xq7NJGAzGZZx8PhwBRsl9CN0IZToU',
    appId: '1:707418014205:ios:d8d4e20652abb325645994',
    messagingSenderId: '707418014205',
    projectId: 'isometric-playground-321',
    storageBucket: 'isometric-playground-321.firebasestorage.app',
    iosBundleId: 'com.example.isometricPlayground',
  );
}
